# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmt < Formula
  desc "A Go-based tool for generating conventional commit messages using AI models via Ollama"
  homepage "https://github.com/dakoctba/cmt"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dakoctba/cmt/releases/download/v1.0.3/cmt_Darwin_x86_64.zip"
      sha256 "a55813902bd8ce384e71aaf8a32895ae08715172375cea1e59828dca71566efe"

      def install
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dakoctba/cmt/releases/download/v1.0.3/cmt_Darwin_arm64.zip"
      sha256 "d9a0b431b7aab8dd030a2ecb01203b98c35d631ff226986db834bd67df0701a5"

      def install
        bin.install "cmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dakoctba/cmt/releases/download/v1.0.3/cmt_Linux_x86_64.tar.gz"
        sha256 "7fa2a3e2e0c9b341664de49134e588e4e17697afe2e1155b05d3ce207e5d1d40"

        def install
          bin.install "cmt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dakoctba/cmt/releases/download/v1.0.3/cmt_Linux_arm64.tar.gz"
        sha256 "52dde25b86fe701d17f89693cc8787fb57adb2ea07d382a46bdf22ddedb57455"

        def install
          bin.install "cmt"
        end
      end
    end
  end

  test do
    system "#{bin}/cmt", "--version"
  end
end
