# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redup < Formula
  desc "Duplicate File Manager - A CLI tool to find and manage duplicate files by content"
  homepage "https://github.com/dakoctba/redup"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dakoctba/redup/releases/download/v1.0.6/redup_Darwin_x86_64.zip"
      sha256 "175abb182b214afc37f9ee6ad2caf911fd089053eadd46b467810d33998275a3"

      def install
        bin.install "redup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dakoctba/redup/releases/download/v1.0.6/redup_Darwin_arm64.zip"
      sha256 "426265f6e24062e294a11be4ca967c1d6361236a4c3e5442dc40030a9d671f16"

      def install
        bin.install "redup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dakoctba/redup/releases/download/v1.0.6/redup_Linux_x86_64.tar.gz"
        sha256 "78bf2072902877d86337eaa61c567edda4adf0c6d5ef52bae29bc136ecbcde9e"

        def install
          bin.install "redup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dakoctba/redup/releases/download/v1.0.6/redup_Linux_arm64.tar.gz"
        sha256 "e2967af39b11c5725f5e8f4867ed1c6b8f17f6b4d80be9be49c024ab07534ada"

        def install
          bin.install "redup"
        end
      end
    end
  end

  test do
    system "#{bin}/redup", "--version"
  end
end
