# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redup < Formula
  desc "Duplicate File Manager - A CLI tool to find and manage duplicate files by content"
  homepage "https://github.com/dakoctba/redup"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dakoctba/redup/releases/download/v1.0.7/redup_Darwin_x86_64.zip"
      sha256 "299e66dbfb78a93e4ca10e1c029e562699829bef4461c0586585ec6511345ec2"

      def install
        bin.install "redup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dakoctba/redup/releases/download/v1.0.7/redup_Darwin_arm64.zip"
      sha256 "17a936a7f20e1e78a146280d8ee89bbd1a55ed9d59707f60c587f2fa77bc3919"

      def install
        bin.install "redup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dakoctba/redup/releases/download/v1.0.7/redup_Linux_x86_64.tar.gz"
        sha256 "eaef4c99264ee5450581be2e32267cd3e886ef503ac13364aed6c0461b7c79e6"

        def install
          bin.install "redup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dakoctba/redup/releases/download/v1.0.7/redup_Linux_arm64.tar.gz"
        sha256 "4d9881bebd69c1871871617744995708742e61b7d6478e31ccdfd707f004cbcd"

        def install
          bin.install "redup"
        end
      end
    end
  end

  test do
    system "#{bin}/redup", "--version"
  end
end
